In [8]:
import torch as th


In [26]:
a = torch.arange(9)
b =  torch.arange(9)
a.dot(b)

tensor(204)

In [28]:
a = th.reshape(a, (3,3))
b = th.reshape(b, (3, 3))

In [22]:
print(a)
print(b)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [19]:
a*b

tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])

In [20]:
a@b

tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [23]:
a.dot(b)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors